name: Release

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Run GoReleaser for unix based
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          goos:
            - linux
            - darwin
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser for Windows
        uses: goreleaser/goreleaser-action@v2
        platform: windows
        with:
          distribution: goreleaser
          version: latest
          goos:
            - windows
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}